# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: azure-deveops-ispw-operation-task@2
  inputs:
    connectionId: 'cw09.bmc.com:47623#1047 - Latin 1 (Open Systems)'
    operationType: 'ISPWSYNC'
    windowsWorkbenchCliHome: 'C:\WorkbenchCLI'
    runtimeConfiguration: 'tpzp'
    ispwusername: 'ispwtpz'
    ispwpassword: 'ispw13'
    stream: 'play'
    application: 'play'
    encryptionProtocol: 'NONE'
    codePage: '1047 - Latin 1 (Open Systems)'
    branchMapping: '**/main => DEV1, per-commit'